task:
  matrix:
    - name: python3
      container:
        matrix:
          - image: python:3.6
          - image: python:latest
      tcl_evalfile_script:
        - python -c "import tkinter; tkinter.Tcl().tk.evalfile('sqlite-undoredo.tcl')"
      python_lint_script:
        - python -m pip install flake8
        - python -m flake8
      python_test_script:
        - python -m pip install apsw
        - python python3/test_sqlite_undoredo.py

    - name: cpp17
      container:
        image: kunitoki/clang-9:latest
      cpp_format_script:
        - clang-format -version
        - 'git ls-files cpp17/"*."{cpp,hpp} | xargs -d\\n clang-format -i -style=file -verbose'
        - git diff --exit-code
      cpp_test_script:
        - cmake -S cpp17 -B cpp17/build
        - cmake --build cpp17/build
        - (cd cpp17/build && ctest)
